#!/usr/bin/env python3

import argparse
import collections
import itertools
import os
import subprocess
import sys
import urllib.request

# Script URL
script_name = 'gitkit'
script_url = f'https://raw.githubusercontent.com/martin-ockajak/git-kit/main/{script_name}'


# Entry point
def main() -> int:
  commands['kit'] = ('List Git aliases invoking Git Kit commands.', kit)
  commands['install'] = ('Install Git command aliases invoking Git Kit commands.', install)
  command = parse_arguments(sys.argv[1:min(len(sys.argv), 2)], commands)
  commands[command][1](command, commands[command][0], sys.argv[2:])
  return 0


# Parse command-line arguments
def parse_arguments(arguments: list[str], commands: dict[str, (str, str)]) -> str:
  parser = argparse.ArgumentParser(
    description = 'Invoke additional Git commands.',
    usage = '''
  %(prog)s <command> [arguments] - Invoke specified command.
  %(prog)s <command> -h          - Display specified command help.''',
    formatter_class = argparse.ArgumentDefaultsHelpFormatter
  )
  command_names = commands.keys()
  parser.add_argument(
    'command',
    metavar = '<command>',
    nargs = 1,
    choices = command_names,
    help = f'Available: {", ".join(command_names)}'
)
  return parser.parse_args(arguments).command[0]


# Fuse command.
def fuse(command: str, description: str, arguments: list[str]) -> None:
  # Parse arguments
  parser = argparse.ArgumentParser(
    usage = f'%(prog)s {command}',
    description = description,
    formatter_class = argparse.ArgumentDefaultsHelpFormatter
  )
  parser.add_argument(
    '-a',
    '--all',
    action = "store_true",
    help = 'Pull changes from all remote branches and push changes to the current branch.'
  )
  parser.add_argument(
    '-p',
    '--prune',
    action = "store_true",
    help = 'Delete local branches which track non-existent remote branches.'
  )
  options = parser.parse_args(arguments)

  # List branches
  local_branches = list_local_branches()
  remote_branches = list_remote_branches()
  local_tracking_branches = list_local_tracking_branches()
  default_branch = get_default_branch()
  current_branch = get_current_branch()

  # Publish current local-only branch
  if current_branch not in local_tracking_branches:
    publish_changes(upstream_branch = current_branch)

  # Track untracked remote branches
  if options.all:
    new_remote_branches = sorted(list(set(remote_branches) - set(local_branches)))
    track_remote_branches(new_remote_branches)

  # Retrieve changes to all branches if possible
  retrieve_changes(current_branch, default_branch)

  # Delete local branches tracking non-existent remote branches
  if options.prune:
    old_local_branches = list(set(local_tracking_branches) - set(remote_branches) - set(current_branch))
    delete_branches(old_local_branches)

  # Publish changes to the current branch
  if current_branch in local_tracking_branches:
    publish_changes()


# Amend command.
def amend(command: str, description: str, arguments: list[str]) -> None:
  subprocess.check_call(['git', 'commit', '--amend', '-C', 'HEAD'])


# Pull merge command.
def pullmerge(command: str, description: str, arguments: list[str]) -> None:
  if not arguments:
    raise Exception('Missing branch name')
  branch = arguments[0]
  current_branch = get_current_branch()
  default_branch = get_default_branch()
  if branch == current_branch:
    raise Exception('Invalid branch name')

  # Retrieve changes to the source branch
  retrieve_changes(current_branch, default_branch, current_branch_only = True)

  # Retrieve changes to the target branch
  subprocess.check_call(['git', 'checkout', branch])
  retrieve_changes(branch, default_branch, current_branch_only = True)

  # Perform the merge command
  subprocess.check_call(['git', 'checkout', current_branch])
  subprocess.check_call(['git', 'merge', branch] + arguments[1:])


# Blank merge command.
def blankmerge(command: str, description: str, arguments: list[str]) -> None:
  if not arguments:
    raise Exception('Missing branch name')
  branch = arguments[0]
  subprocess.check_call(['git', 'merge', '-s', 'ours', '--no-editlog'] + arguments[1:])


# Graph log command.
def graphlog(command: str, description: str, arguments: list[str]) -> None:
  subprocess.check_call(['git', 'log', '--all', '--graph', '--stat', '--pretty=format:%C(ul red)%h%C(reset) -%C(yellow)%d%C(reset) %C(cyan)%s%C(reset) %C(bold blue)<%an>%C(reset) %C(magenta)(%cr)%C(reset)', '--abbrev-commit'] + arguments)

# Branch log command.
def branchlog(command: str, description: str, arguments: list[str]) -> None:
  branch = arguments[0] if arguments else get_current_branch()
  subprocess.check_call(['git', 'log', '--stat', '--pretty=format:%C(ul red)%h%C(reset) -%C(yellow)%d%C(reset) %C(cyan)%s%C(reset) %C(bold blue)<%an>%C(reset) %C(magenta)(%cr)%C(reset)', '--abbrev-commit', '--first-parent', branch] + arguments[1:])

commands = collections.OrderedDict([
  ('fuse', ('Pull changes from all remote branches and push changes to the current branch.', fuse)),
  ('amend', ('Add staged changes to the last commit.', amend)),
  ('pullmerge', ('Merge a branch into the current branch using the last revision of both branches.', pullmerge)),
  ('blankmerge', ('Merge a branch into the current branch without applying any changes.', blankmerge)),
  ('graphlog', ('Display commit log for all branches as a graph.', graphlog)),
  ('branchlog', ('Display commit log for specified branch only.', branchlog)),
])


# Kit command.
def kit(command: str, description: str, arguments: list[str]) -> None:
  print('Git aliases invoking Git Kit commands:\n')
  for alias, (description, _) in commands.items():
    if alias != 'install':
      print(f'* {alias} - {description}')
  print('''
  git <command> [arguments] - Perform specified command.
  git <command> -h          - Display specified command help.
''')


# Install into current Git repository.
def install(command: str, description: str, arguments: list[str]) -> None:
  # Parse arguments
  parser = argparse.ArgumentParser(
    usage = f'%(prog)s {command} [repository]',
    description = description,
    formatter_class = argparse.ArgumentDefaultsHelpFormatter
  )
  parser.add_argument(
    'repository',
    metavar = 'repository',
    nargs = '?',
    default = '.',
    help = 'Git repository path.'
  )
  options = parser.parse_args(arguments)
  script_path = os.path.abspath(os.path.join(options.repository, '.git', script_name))
  with urllib.request.urlopen(script_url) as source:
    with open(script_path, 'w+') as script_file:
      script_file.write(source.read().decode('utf-8'))
  for alias, (description, _) in commands.items():
    if alias != command:
      path = script_path.replace('\\', '\\\\')
      command_line = f'!python3 {path} {alias} $@'
      subprocess.check_call(['git', 'config', f'alias.{alias}', command_line], stdout = subprocess.PIPE)
  subprocess.check_call(['git', 'remote', 'set-head' , 'origin', '--auto'])
  print(f'Installed: {script_path}\n')
  kit('', '', [])


# Fetch changes to all branches if possible and merge the fetched changes to the current branch
def retrieve_changes(current_branch: str, default_branch: str, current_branch_only = False) -> None:
  extra_remotes = list_extra_remotes()

  # Retrieve changes for the current branch and use alternative remote for the default branch if available
  specific_remote = [extra_remotes[0], current_branch] if current_branch == default_branch and extra_remotes else []
  if current_branch_only or specific_remote:
    subprocess.check_call(['git', 'pull', '--prune'] + specific_remote)
  else:
    # Retrieve changes for all branches
    subprocess.check_call(['git', 'fetch', '--all', '--prune', '--prune-tags'])
    subprocess.check_call(['git', 'merge', 'FETCH_HEAD'])


# Publish changes to all branches
def publish_changes(upstream_branch: str = None) -> None:
  set_upstream_option = ['-u', 'origin', upstream_branch] if upstream_branch else []
  subprocess.check_call(['git', 'push', '--follow-tags'] + set_upstream_option)


# List remote repositories other than origin.
def list_extra_remotes():
  remotes = execute_as_lines(['git', 'remote'])
  remotes.remove('origin')
  return remotes


# List remote branches
def list_remote_branches(remote: bool = False, merged_branch: str = None) -> list[str]:
  lines = execute_as_lines(['git', 'remote', 'show', 'origin'])
  entries = [line.split() for line in lines]
  branches = [entry[0] for entry in entries if entry[1] == 'tracked']
  return branches


# List local branches merge state
def list_local_branches(merged_branch: str = None) -> list[str]:
  merged_option = (['--merged', merged_branch] if merged_branch else [])
  lines = execute_as_lines(['git', 'branch'] + merged_option)
  branches = [line for line in lines if line]
  current_branch = next((branch for branch in branches if branch.startswith('*')), None)
  if current_branch:
    branches.remove(current_branch)
    branches.insert(0, current_branch[1:].strip())
  return branches


# List local branches which track remote branches
def list_local_tracking_branches() -> list[str]:
  lines = execute_as_lines(['git', 'branch', '-lvv'])
  branches = []
  for line in lines:
    fields = line.split()
    if len(fields) > 2:
      if fields[0] == '*':
        fields = fields[1:]
      if fields[2].startswith('[origin') and (fields[2].endswith(']') or fields[2].endswith(':')):
        branches.append(fields[0])
  return branches


# Create local branches to track specified remote branches
def track_remote_branches(branches: list[str]) -> None:
  for branch in branches:
    subprocess.check_call(['git', 'branch', '-t', branch, f'origin/{branch}'], stdout = subprocess.PIPE)
  if branches:
    branch_list = ''.join(['  %s\n' % branch for branch in branches])
    print(f'Fetched remote branches:\n{branch_list}')


# Delete specified branches
def delete_branches(branches: list[str]) -> None:
  for branch in branches:
    subprocess.check_call(['git', 'branch', '-D', branch], stdout = subprocess.PIPE)
  if branches:
    branch_list = ''.join(['  %s\n' % branch for branch in branches])
    print(f'Deleted local branches:\n{branch_list}')


# Determine default branch.
def get_default_branch() -> str:
  lines = execute_as_lines(['git', 'symbolic-ref', '--short', 'refs/remotes/origin/HEAD'])
  return lines[0].split('/', 1)[1]


# Determine current branch.
def get_current_branch() -> str:
  return execute_as_lines(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])[0]


# Execute command and parse its output into lines without surrounding whitespace or empty lines.
def execute_as_lines(command: list[str]) -> list[str]:
  output = subprocess.check_output(command).decode("utf-8")
  lines = list(itertools.takewhile(lambda line: line, itertools.dropwhile(lambda line: not line, output.split('\n'))))
  return [line.strip() for line in lines]


if __name__ == "__main__":
  sys.exit(main())

